name: uv_forecast
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pandas
  - numpy
  - requests
  - pvlib
  - python-dotenv
  - tqdm
  - scikit-learn
  - xgboost
  - lightgbm
  - pytorch
  - matplotlib
  - seaborn
  - ipykernel
  - scipy
  - optuna
  - joblib
  - mlflow
  - statsmodels
  - pip
  - pip:
    - streamlit
    - plotly
    - shap
    - catboost
    - prophet
    - databricks-sdk
    - folium
    - streamlit-folium